export default {
  '17896441': [() => import(/* webpackChunkName: '17896441' */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  '1be78505': [() => import(/* webpackChunkName: '1be78505' */ "@theme/DocPage"), "@theme/DocPage", require.resolveWeak("@theme/DocPage")],
  '3748c412': [() => import(/* webpackChunkName: '3748c412' */ "@site/src\\pages\\help.js"), "@site/src\\pages\\help.js", require.resolveWeak("@site/src\\pages\\help.js")],
  '56afd8a3': [() => import(/* webpackChunkName: '56afd8a3' */ "@site/..\\website-docs\\faq.md"), "@site/..\\website-docs\\faq.md", require.resolveWeak("@site/..\\website-docs\\faq.md")],
  '5a1831e4': [() => import(/* webpackChunkName: '5a1831e4' */ "@site/..\\website-docs\\implementations.md"), "@site/..\\website-docs\\implementations.md", require.resolveWeak("@site/..\\website-docs\\implementations.md")],
  '5c4ee1d6': [() => import(/* webpackChunkName: '5c4ee1d6' */ "~blog/default\\blog-c06.json"), "~blog/default\\blog-c06.json", require.resolveWeak("~blog/default\\blog-c06.json")],
  '5e9f5e1a': [() => import(/* webpackChunkName: '5e9f5e1a' */ "@generated/docusaurus.config"), "@generated/docusaurus.config", require.resolveWeak("@generated/docusaurus.config")],
  '73c48262': [() => import(/* webpackChunkName: '73c48262' */ "@site/..\\website-docs\\motivations.md"), "@site/..\\website-docs\\motivations.md", require.resolveWeak("@site/..\\website-docs\\motivations.md")],
  '803825b0': [() => import(/* webpackChunkName: '803825b0' */ "@site/..\\website-docs\\protocol.md"), "@site/..\\website-docs\\protocol.md", require.resolveWeak("@site/..\\website-docs\\protocol.md")],
  '833e6c8b': [() => import(/* webpackChunkName: '833e6c8b' */ "E:\\dev\\rsocket-website\\website-v2\\.docusaurus\\docusaurus-plugin-content-blog\\default\\blog-post-list-prop-default.json"), "E:\\dev\\rsocket-website\\website-v2\\.docusaurus\\docusaurus-plugin-content-blog\\default\\blog-post-list-prop-default.json", require.resolveWeak("E:\\dev\\rsocket-website\\website-v2\\.docusaurus\\docusaurus-plugin-content-blog\\default\\blog-post-list-prop-default.json")],
  'a6aa9e1f': [() => import(/* webpackChunkName: 'a6aa9e1f' */ "@theme/BlogListPage"), "@theme/BlogListPage", require.resolveWeak("@theme/BlogListPage")],
  'a9b0b7cd': [() => import(/* webpackChunkName: 'a9b0b7cd' */ "@site/blog\\2018-10-08.md?truncated=true"), "@site/blog\\2018-10-08.md?truncated=true", require.resolveWeak("@site/blog\\2018-10-08.md?truncated=true")],
  'ccc49370': [() => import(/* webpackChunkName: 'ccc49370' */ "@theme/BlogPostPage"), "@theme/BlogPostPage", require.resolveWeak("@theme/BlogPostPage")],
  'e3c38544': [() => import(/* webpackChunkName: 'e3c38544' */ "@site/blog\\2018-10-08.md"), "@site/blog\\2018-10-08.md", require.resolveWeak("@site/blog\\2018-10-08.md")],
  'ece76bd1': [() => import(/* webpackChunkName: 'ece76bd1' */ "@site/src\\pages\\index.js"), "@site/src\\pages\\index.js", require.resolveWeak("@site/src\\pages\\index.js")],
  'f976f453': [() => import(/* webpackChunkName: 'f976f453' */ "~docs/default\\version-current-metadata-prop-751.json"), "~docs/default\\version-current-metadata-prop-751.json", require.resolveWeak("~docs/default\\version-current-metadata-prop-751.json")],};
